services:
  grafana:
    build:
      context: .
      dockerfile: grafana.Dockerfile
    ports:
      - 3000:3000
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: https://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
      GF_ROOT_URL: https://grafana:3000/

  renderer:
    build:
      context: .
      dockerfile: renderer.Dockerfile
    ports:
      - 8081
    environment:
      ENABLE_METRICS: 'true'
