apiVersion: 1

datasources:
  - name: Testdata
    isDefault: true
    type: testdata

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      timeInterval: 10s
      queryTimeout: 30s
      httpMethod: POST
