---
kind: pipeline
type: docker
name: test-pr

platform:
  os: linux
  arch: amd64

steps:
- name: grabpl
  image: byrnedo/alpine-curl:0.1.8
  commands:
  - mkdir -p bin
  - curl -fL -o bin/grabpl https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v3.0.20/grabpl
  - chmod +x bin/grabpl

- name: yarn-install
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - yarn install --frozen-lockfile --no-progress
  depends_on:
  - grabpl

- name: yarn-build
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - yarn build
  depends_on:
  - yarn-install

- name: package-linux-x64-glibc
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - sh scripts/package_target.sh linux-x64-glibc
  - bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc || true
  - sh scripts/archive_target.sh linux-x64-glibc
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  depends_on:
  - yarn-build

- name: package-darwin-x64-unknown
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - sh scripts/package_target.sh darwin-x64-unknown
  - bin/grabpl build-plugin-manifest ./dist/plugin-darwin-x64-unknown || true
  - sh scripts/archive_target.sh darwin-x64-unknown
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  depends_on:
  - yarn-build

- name: package-win32-x64-unknown
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - sh scripts/package_target.sh win32-x64-unknown
  - bin/grabpl build-plugin-manifest ./dist/plugin-win32-x64-unknown || true
  - sh scripts/archive_target.sh win32-x64-unknown
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  depends_on:
  - yarn-build

- name: package-linux-x64-glibc-no-chromium
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - sh scripts/package_target.sh linux-x64-glibc true plugin-linux-x64-glibc-no-chromium
  - bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc-no-chromium || true
  - sh scripts/archive_target.sh linux-x64-glibc plugin-linux-x64-glibc-no-chromium
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  depends_on:
  - yarn-build

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

image_pull_secrets:
- dockerconfigjson

node:
  type: no-parallel

trigger:
  event:
  - pull_request

---
kind: pipeline
type: docker
name: test-master

platform:
  os: linux
  arch: amd64

steps:
- name: grabpl
  image: byrnedo/alpine-curl:0.1.8
  commands:
  - mkdir -p bin
  - curl -fL -o bin/grabpl https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v3.0.20/grabpl
  - chmod +x bin/grabpl

- name: yarn-install
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - yarn install --frozen-lockfile --no-progress
  depends_on:
  - grabpl

- name: yarn-build
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - yarn build
  depends_on:
  - yarn-install

- name: package-linux-x64-glibc
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - sh scripts/package_target.sh linux-x64-glibc
  - bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc
  - sh scripts/archive_target.sh linux-x64-glibc
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  depends_on:
  - yarn-build

- name: package-darwin-x64-unknown
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - sh scripts/package_target.sh darwin-x64-unknown
  - bin/grabpl build-plugin-manifest ./dist/plugin-darwin-x64-unknown
  - sh scripts/archive_target.sh darwin-x64-unknown
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  depends_on:
  - yarn-build

- name: package-win32-x64-unknown
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - sh scripts/package_target.sh win32-x64-unknown
  - bin/grabpl build-plugin-manifest ./dist/plugin-win32-x64-unknown
  - sh scripts/archive_target.sh win32-x64-unknown
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  depends_on:
  - yarn-build

- name: package-linux-x64-glibc-no-chromium
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - sh scripts/package_target.sh linux-x64-glibc true plugin-linux-x64-glibc-no-chromium
  - bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc-no-chromium
  - sh scripts/archive_target.sh linux-x64-glibc plugin-linux-x64-glibc-no-chromium
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  depends_on:
  - yarn-build

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

image_pull_secrets:
- dockerconfigjson

node:
  type: no-parallel

trigger:
  branch:
  - master
  event:
  - push

---
kind: pipeline
type: docker
name: release

platform:
  os: linux
  arch: amd64

steps:
- name: grabpl
  image: byrnedo/alpine-curl:0.1.8
  commands:
  - mkdir -p bin
  - curl -fL -o bin/grabpl https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v3.0.20/grabpl
  - chmod +x bin/grabpl

- name: yarn-install
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - yarn install --frozen-lockfile --no-progress
  depends_on:
  - grabpl

- name: yarn-build
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - yarn build
  depends_on:
  - yarn-install

- name: package-linux-x64-glibc
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - sh scripts/package_target.sh linux-x64-glibc
  - bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc
  - sh scripts/archive_target.sh linux-x64-glibc
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  depends_on:
  - yarn-build

- name: package-darwin-x64-unknown
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - sh scripts/package_target.sh darwin-x64-unknown
  - bin/grabpl build-plugin-manifest ./dist/plugin-darwin-x64-unknown
  - sh scripts/archive_target.sh darwin-x64-unknown
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  depends_on:
  - yarn-build

- name: package-win32-x64-unknown
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - sh scripts/package_target.sh win32-x64-unknown
  - bin/grabpl build-plugin-manifest ./dist/plugin-win32-x64-unknown
  - sh scripts/archive_target.sh win32-x64-unknown
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  depends_on:
  - yarn-build

- name: package-linux-x64-glibc-no-chromium
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - sh scripts/package_target.sh linux-x64-glibc true plugin-linux-x64-glibc-no-chromium
  - bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc-no-chromium
  - sh scripts/archive_target.sh linux-x64-glibc plugin-linux-x64-glibc-no-chromium
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  depends_on:
  - yarn-build

- name: publish_to_github
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - sh scripts/generate_md5sum.sh
  - sh scripts/publish_github_release.sh
  depends_on:
  - package-linux-x64-glibc
  - package-darwin-x64-unknown
  - package-win32-x64-unknown
  - package-linux-x64-glibc-no-chromium

- name: publish_to_docker
  image: google/cloud-sdk:412.0.0
  commands:
  - sh scripts/build_push_docker.sh master
  environment:
    DOCKER_PASS:
      from_secret: docker_pass
    DOCKER_USER:
      from_secret: docker_user
    IMAGE_NAME: grafana/grafana-image-renderer
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: publish_to_grafana
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - yarn run create-gcom-plugin-json ${DRONE_COMMIT}
  - sh scripts/push-to-gcom.sh
  depends_on:
  - package-linux-x64-glibc
  - package-darwin-x64-unknown
  - package-win32-x64-unknown
  - package-linux-x64-glibc-no-chromium

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

image_pull_secrets:
- dockerconfigjson

node:
  type: no-parallel

trigger:
  event:
  - promote
  target:
  - release

---
kind: pipeline
type: docker
name: perform-srcclr-scan

platform:
  os: linux
  arch: amd64

steps:
- name: security-scan
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - echo "Starting veracode scan..."
  - apk add curl
  - "# Increase heap size or the scanner will die."
  - export _JAVA_OPTIONS=-Xmx4g
  - mkdir -p ci/jobs/security_scan
  - curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --skip-compile --quick --allow-dirty
  failure: ignore

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

image_pull_secrets:
- dockerconfigjson

node:
  type: no-parallel

trigger:
  branch:
  - master
  event:
  - push

---
kind: secret
name: dockerconfigjson

get:
  path: secret/data/common/gcr
  name: .dockerconfigjson

---
kind: secret
name: github_token

get:
  path: infra/data/ci/drone-plugins
  name: github_token

---
kind: secret
name: grafana_api_key

get:
  path: infra/data/ci/drone-plugins
  name: grafana_api_key

---
kind: secret
name: srcclr_api_token

get:
  path: infra/data/ci/drone-plugins
  name: srcclr_api_token

---
kind: signature
hmac: 42c8e9537ca0762b597ac85ac13cb08e5a6dbe43c8487174d82a19602a9208d5

...
