---
clone:
  retries: 3
depends_on: []
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: test-pr
node:
  type: no-parallel
platform:
  arch: amd64
  os: linux
services: []
steps:
- commands:
  - mkdir -p bin
  - curl -fL -o bin/grabpl https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v3.0.20/grabpl
  - chmod +x bin/grabpl
  image: byrnedo/alpine-curl:0.1.8
  name: grabpl
- commands:
  - . ~/.init-nvm.sh
  - yarn install --frozen-lockfile --no-progress
  depends_on:
  - grabpl
  image: grafana/grafana-plugin-ci:1.9.0
  name: yarn-install
- commands:
  - . ~/.init-nvm.sh
  - yarn build
  depends_on:
  - yarn-install
  image: grafana/grafana-plugin-ci:1.9.0
  name: yarn-build
- commands:
  - . ~/.init-nvm.sh
  - echo "Starting veracode scan..."
  - '# Increase heap size or the scanner will die.'
  - export _JAVA_OPTIONS=-Xmx4g
  - mkdir -p ci/jobs/security_scan
  - curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --skip-compile --quick
    --allow-dirty
  depends_on:
  - yarn-build
  environment:
    SRCCLR_API_TOKEN:
      from_secret: srcclr_api_token
  failure: ignore
  image: grafana/grafana-plugin-ci:1.9.0
  name: security-scan
- commands:
  - . ~/.init-nvm.sh
  - sh scripts/package_target.sh linux-x64-glibc
  - bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc || true
  - sh scripts/archive_target.sh linux-x64-glibc
  depends_on:
  - yarn-build
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-linux-x64-glibc
- commands:
  - . ~/.init-nvm.sh
  - sh scripts/package_target.sh darwin-x64-unknown
  - bin/grabpl build-plugin-manifest ./dist/plugin-darwin-x64-unknown || true
  - sh scripts/archive_target.sh darwin-x64-unknown
  depends_on:
  - yarn-build
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-darwin-x64-unknown
- commands:
  - . ~/.init-nvm.sh
  - sh scripts/package_target.sh win32-x64-unknown
  - bin/grabpl build-plugin-manifest ./dist/plugin-win32-x64-unknown || true
  - sh scripts/archive_target.sh win32-x64-unknown
  depends_on:
  - yarn-build
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-win32-x64-unknown
- commands:
  - . ~/.init-nvm.sh
  - sh scripts/package_target.sh linux-x64-glibc true plugin-linux-x64-glibc-no-chromium
  - bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc-no-chromium ||
    true
  - sh scripts/archive_target.sh linux-x64-glibc plugin-linux-x64-glibc-no-chromium
  depends_on:
  - yarn-build
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-linux-x64-glibc-no-chromium
trigger:
  event:
  - pull_request
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
clone:
  retries: 3
depends_on: []
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: test-master
node:
  type: no-parallel
platform:
  arch: amd64
  os: linux
services: []
steps:
- commands:
  - mkdir -p bin
  - curl -fL -o bin/grabpl https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v3.0.20/grabpl
  - chmod +x bin/grabpl
  image: byrnedo/alpine-curl:0.1.8
  name: grabpl
- commands:
  - . ~/.init-nvm.sh
  - yarn install --frozen-lockfile --no-progress
  depends_on:
  - grabpl
  image: grafana/grafana-plugin-ci:1.9.0
  name: yarn-install
- commands:
  - . ~/.init-nvm.sh
  - yarn build
  depends_on:
  - yarn-install
  image: grafana/grafana-plugin-ci:1.9.0
  name: yarn-build
- commands:
  - . ~/.init-nvm.sh
  - echo "Starting veracode scan..."
  - '# Increase heap size or the scanner will die.'
  - export _JAVA_OPTIONS=-Xmx4g
  - mkdir -p ci/jobs/security_scan
  - curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --skip-compile --quick
    --allow-dirty
  depends_on:
  - yarn-build
  environment:
    SRCCLR_API_TOKEN:
      from_secret: srcclr_api_token
  failure: ignore
  image: grafana/grafana-plugin-ci:1.9.0
  name: security-scan
- commands:
  - . ~/.init-nvm.sh
  - sh scripts/package_target.sh linux-x64-glibc
  - bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc
  - sh scripts/archive_target.sh linux-x64-glibc
  depends_on:
  - yarn-build
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-linux-x64-glibc
- commands:
  - . ~/.init-nvm.sh
  - sh scripts/package_target.sh darwin-x64-unknown
  - bin/grabpl build-plugin-manifest ./dist/plugin-darwin-x64-unknown
  - sh scripts/archive_target.sh darwin-x64-unknown
  depends_on:
  - yarn-build
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-darwin-x64-unknown
- commands:
  - . ~/.init-nvm.sh
  - sh scripts/package_target.sh win32-x64-unknown
  - bin/grabpl build-plugin-manifest ./dist/plugin-win32-x64-unknown
  - sh scripts/archive_target.sh win32-x64-unknown
  depends_on:
  - yarn-build
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-win32-x64-unknown
- commands:
  - . ~/.init-nvm.sh
  - sh scripts/package_target.sh linux-x64-glibc true plugin-linux-x64-glibc-no-chromium
  - bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc-no-chromium
  - sh scripts/archive_target.sh linux-x64-glibc plugin-linux-x64-glibc-no-chromium
  depends_on:
  - yarn-build
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-linux-x64-glibc-no-chromium
- commands:
  - sh scripts/build_push_docker.sh master
  environment:
    DOCKER_PASS:
      from_secret: docker_pass
    DOCKER_USER:
      from_secret: docker_user
    IMAGE_NAME: grafana/grafana-image-renderer
  image: google/cloud-sdk:412.0.0
  name: publish_to_docker_master
  volumes:
  - name: docker
    path: /var/run/docker.sock
trigger:
  branch:
  - master
  event:
  - push
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
clone:
  retries: 3
depends_on: []
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: release
node:
  type: no-parallel
platform:
  arch: amd64
  os: linux
services: []
steps:
- commands:
  - mkdir -p bin
  - curl -fL -o bin/grabpl https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v3.0.20/grabpl
  - chmod +x bin/grabpl
  image: byrnedo/alpine-curl:0.1.8
  name: grabpl
- commands:
  - . ~/.init-nvm.sh
  - yarn install --frozen-lockfile --no-progress
  depends_on:
  - grabpl
  image: grafana/grafana-plugin-ci:1.9.0
  name: yarn-install
- commands:
  - . ~/.init-nvm.sh
  - yarn build
  depends_on:
  - yarn-install
  image: grafana/grafana-plugin-ci:1.9.0
  name: yarn-build
- commands:
  - . ~/.init-nvm.sh
  - echo "Starting veracode scan..."
  - '# Increase heap size or the scanner will die.'
  - export _JAVA_OPTIONS=-Xmx4g
  - mkdir -p ci/jobs/security_scan
  - curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --skip-compile --quick
    --allow-dirty
  depends_on:
  - yarn-build
  environment:
    SRCCLR_API_TOKEN:
      from_secret: srcclr_api_token
  failure: ignore
  image: grafana/grafana-plugin-ci:1.9.0
  name: security-scan
- commands:
  - . ~/.init-nvm.sh
  - sh scripts/package_target.sh linux-x64-glibc
  - bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc
  - sh scripts/archive_target.sh linux-x64-glibc
  depends_on:
  - yarn-build
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-linux-x64-glibc
- commands:
  - . ~/.init-nvm.sh
  - sh scripts/package_target.sh darwin-x64-unknown
  - bin/grabpl build-plugin-manifest ./dist/plugin-darwin-x64-unknown
  - sh scripts/archive_target.sh darwin-x64-unknown
  depends_on:
  - yarn-build
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-darwin-x64-unknown
- commands:
  - . ~/.init-nvm.sh
  - sh scripts/package_target.sh win32-x64-unknown
  - bin/grabpl build-plugin-manifest ./dist/plugin-win32-x64-unknown
  - sh scripts/archive_target.sh win32-x64-unknown
  depends_on:
  - yarn-build
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-win32-x64-unknown
- commands:
  - . ~/.init-nvm.sh
  - sh scripts/package_target.sh linux-x64-glibc true plugin-linux-x64-glibc-no-chromium
  - bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc-no-chromium
  - sh scripts/archive_target.sh linux-x64-glibc plugin-linux-x64-glibc-no-chromium
  depends_on:
  - yarn-build
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-linux-x64-glibc-no-chromium
- commands:
  - sh scripts/generate_md5sum.sh
  - sh scripts/publish_github_release.sh
  depends_on:
  - package-linux-x64-glibc
  - package-darwin-x64-unknown
  - package-win32-x64-unknown
  - package-linux-x64-glibc-no-chromium
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  image: cibuilds/github:0.13.0
  name: publish_to_github
- commands:
  - sh scripts/build_push_docker.sh
  depends_on:
  - publish_to_github
  environment:
    DOCKER_PASS:
      from_secret: docker_pass
    DOCKER_USER:
      from_secret: docker_user
    IMAGE_NAME: grafana/grafana-image-renderer
  image: google/cloud-sdk:412.0.0
  name: publish_to_docker
  volumes:
  - name: docker
    path: /var/run/docker.sock
- commands:
  - . ~/.init-nvm.sh
  - yarn run create-gcom-plugin-json ${DRONE_COMMIT}
  - sh scripts/push-to-gcom.sh
  depends_on:
  - publish_to_github
  environment:
    GCOM_PUBLISH_TOKEN:
      from_secret: gcom_publish_token
    GCOM_UAGENT:
      from_secret: gcom_uagent
    GCOM_URL:
      from_secret: gcom_url
  image: grafana/grafana-plugin-ci:1.9.0
  name: publish_to_gcom
trigger:
  branch:
  - master
  event:
  - promote
  target:
  - release
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
get:
  name: .dockerconfigjson
  path: secret/data/common/gcr
kind: secret
name: dockerconfigjson
---
get:
  name: github_token
  path: infra/data/ci/drone-plugins
kind: secret
name: github_token
---
get:
  name: gcom_publish_token
  path: infra/data/ci/drone-plugins
kind: secret
name: gcom_publish_token
---
get:
  name: grafana_api_key
  path: infra/data/ci/drone-plugins
kind: secret
name: grafana_api_key
---
get:
  name: srcclr_api_token
  path: infra/data/ci/drone-plugins
kind: secret
name: srcclr_api_token
---
kind: signature
hmac: e6b99f052740c6862015a124564b85182f9877f4eccc159334a40000faf3a008

...
