---
clone:
  retries: 3
depends_on: []
image_pull_secrets:
- gcr
- gar
kind: pipeline
name: test-pr
node:
  type: no-parallel
platform:
  arch: amd64
  os: linux
services:
- environment:
    GF_FEATURE_TOGGLES_ENABLE: renderAuthJWT
    GF_PATHS_PROVISIONING: /drone/src/scripts/drone/provisioning
  image: grafana/grafana-enterprise:latest
  name: grafana
steps:
- commands:
  - mkdir -p bin
  - curl -fL -o bin/grabpl https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v3.0.20/grabpl
  - chmod +x bin/grabpl
  image: byrnedo/alpine-curl:0.1.8
  name: grabpl
- commands:
  - . ~/.init-nvm.sh
  - yarn install --frozen-lockfile --no-progress
  depends_on:
  - grabpl
  environment:
    PUPPETEER_CACHE_DIR: /drone/src/cache
  image: grafana/grafana-plugin-ci:1.9.0
  name: yarn-install
- commands:
  - . ~/.init-nvm.sh
  - yarn build
  depends_on:
  - yarn-install
  image: grafana/grafana-plugin-ci:1.9.0
  name: yarn-build
- commands:
  - dockerize -wait http://grafana:3000 -timeout 120s
  image: jwilder/dockerize:0.6.1
  name: wait-for-grafana
- commands:
  - yarn test-ci
  depends_on:
  - wait-for-grafana
  - yarn-build
  environment:
    CI: "true"
    PUPPETEER_CACHE_DIR: /drone/src/cache
  image: us-docker.pkg.dev/grafanalabs-dev/grafana-ci/docker-puppeteer:2.0.0
  name: yarn-test
- commands:
  - . ~/.init-nvm.sh
  - echo "Starting veracode scan..."
  - '# Increase heap size or the scanner will die.'
  - export _JAVA_OPTIONS=-Xmx4g
  - mkdir -p ci/jobs/security_scan
  - curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --skip-compile --quick
    --allow-dirty
  depends_on:
  - yarn-build
  environment:
    SRCCLR_API_TOKEN:
      from_secret: srcclr_api_token
  failure: ignore
  image: grafana/grafana-plugin-ci:1.9.0
  name: security-scan
- commands:
  - . ~/.init-nvm.sh
  - ./scripts/package_target.sh linux-x64-glibc
  - bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc || true
  - ./scripts/archive_target.sh linux-x64-glibc
  depends_on:
  - yarn-test
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-linux-x64-glibc
- commands:
  - . ~/.init-nvm.sh
  - ./scripts/package_target.sh darwin-x64-unknown
  - bin/grabpl build-plugin-manifest ./dist/plugin-darwin-x64-unknown || true
  - ./scripts/archive_target.sh darwin-x64-unknown
  depends_on:
  - yarn-test
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-darwin-x64-unknown
- commands:
  - . ~/.init-nvm.sh
  - ./scripts/package_target.sh win32-x64-unknown
  - bin/grabpl build-plugin-manifest ./dist/plugin-win32-x64-unknown || true
  - ./scripts/archive_target.sh win32-x64-unknown
  depends_on:
  - yarn-test
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-win32-x64-unknown
- commands:
  - . ~/.init-nvm.sh
  - ./scripts/package_target.sh linux-x64-glibc true plugin-linux-x64-glibc-no-chromium
  - bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc-no-chromium ||
    true
  - ./scripts/archive_target.sh linux-x64-glibc plugin-linux-x64-glibc-no-chromium
  depends_on:
  - yarn-test
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-linux-x64-glibc-no-chromium
- commands:
  - . ~/.init-nvm.sh
  - ./scripts/package_target.sh alpine-x64-unknown true plugin-alpine-x64-no-chromium
  - bin/grabpl build-plugin-manifest ./dist/plugin-alpine-x64-no-chromium || true
  - ./scripts/archive_target.sh alpine-x64-unknown plugin-alpine-x64-no-chromium
  depends_on:
  - yarn-test
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-alpine-x64-no-chromium
trigger:
  event:
  - pull_request
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
clone:
  retries: 3
depends_on: []
image_pull_secrets:
- gcr
- gar
kind: pipeline
name: test-master
node:
  type: no-parallel
platform:
  arch: amd64
  os: linux
services:
- environment:
    GF_FEATURE_TOGGLES_ENABLE: renderAuthJWT
    GF_PATHS_PROVISIONING: /drone/src/scripts/drone/provisioning
  image: grafana/grafana-enterprise:latest
  name: grafana
steps:
- commands:
  - mkdir -p bin
  - curl -fL -o bin/grabpl https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v3.0.20/grabpl
  - chmod +x bin/grabpl
  image: byrnedo/alpine-curl:0.1.8
  name: grabpl
- commands:
  - . ~/.init-nvm.sh
  - yarn install --frozen-lockfile --no-progress
  depends_on:
  - grabpl
  environment:
    PUPPETEER_CACHE_DIR: /drone/src/cache
  image: grafana/grafana-plugin-ci:1.9.0
  name: yarn-install
- commands:
  - . ~/.init-nvm.sh
  - yarn build
  depends_on:
  - yarn-install
  image: grafana/grafana-plugin-ci:1.9.0
  name: yarn-build
- commands:
  - dockerize -wait http://grafana:3000 -timeout 120s
  image: jwilder/dockerize:0.6.1
  name: wait-for-grafana
- commands:
  - yarn test-ci
  depends_on:
  - wait-for-grafana
  - yarn-build
  environment:
    CI: "true"
    PUPPETEER_CACHE_DIR: /drone/src/cache
  image: us-docker.pkg.dev/grafanalabs-dev/grafana-ci/docker-puppeteer:2.0.0
  name: yarn-test
- commands:
  - . ~/.init-nvm.sh
  - echo "Starting veracode scan..."
  - '# Increase heap size or the scanner will die.'
  - export _JAVA_OPTIONS=-Xmx4g
  - mkdir -p ci/jobs/security_scan
  - curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --skip-compile --quick
    --allow-dirty
  depends_on:
  - yarn-build
  environment:
    SRCCLR_API_TOKEN:
      from_secret: srcclr_api_token
  failure: ignore
  image: grafana/grafana-plugin-ci:1.9.0
  name: security-scan
- commands:
  - . ~/.init-nvm.sh
  - ./scripts/package_target.sh linux-x64-glibc
  - bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc
  - ./scripts/archive_target.sh linux-x64-glibc
  depends_on:
  - yarn-test
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-linux-x64-glibc
- commands:
  - . ~/.init-nvm.sh
  - ./scripts/package_target.sh darwin-x64-unknown
  - bin/grabpl build-plugin-manifest ./dist/plugin-darwin-x64-unknown
  - ./scripts/archive_target.sh darwin-x64-unknown
  depends_on:
  - yarn-test
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-darwin-x64-unknown
- commands:
  - . ~/.init-nvm.sh
  - ./scripts/package_target.sh win32-x64-unknown
  - bin/grabpl build-plugin-manifest ./dist/plugin-win32-x64-unknown
  - ./scripts/archive_target.sh win32-x64-unknown
  depends_on:
  - yarn-test
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-win32-x64-unknown
- commands:
  - . ~/.init-nvm.sh
  - ./scripts/package_target.sh linux-x64-glibc true plugin-linux-x64-glibc-no-chromium
  - bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc-no-chromium
  - ./scripts/archive_target.sh linux-x64-glibc plugin-linux-x64-glibc-no-chromium
  depends_on:
  - yarn-test
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-linux-x64-glibc-no-chromium
- commands:
  - . ~/.init-nvm.sh
  - ./scripts/package_target.sh alpine-x64-unknown true plugin-alpine-x64-no-chromium
  - bin/grabpl build-plugin-manifest ./dist/plugin-alpine-x64-no-chromium
  - ./scripts/archive_target.sh alpine-x64-unknown plugin-alpine-x64-no-chromium
  depends_on:
  - yarn-test
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-alpine-x64-no-chromium
- commands:
  - ./scripts/build_push_docker.sh master
  depends_on:
  - yarn-test
  environment:
    DOCKER_PASS:
      from_secret: docker_pass
    DOCKER_USER:
      from_secret: docker_user
    IMAGE_NAME: grafana/grafana-image-renderer
  image: google/cloud-sdk:449.0.0
  name: publish_to_docker_master
  volumes:
  - name: docker
    path: /var/run/docker.sock
trigger:
  branch:
  - master
  event:
  - push
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
clone:
  retries: 3
depends_on: []
image_pull_secrets:
- gcr
- gar
kind: pipeline
name: release
node:
  type: no-parallel
platform:
  arch: amd64
  os: linux
services:
- environment:
    GF_FEATURE_TOGGLES_ENABLE: renderAuthJWT
    GF_PATHS_PROVISIONING: /drone/src/scripts/drone/provisioning
  image: grafana/grafana-enterprise:latest
  name: grafana
steps:
- commands:
  - mkdir -p bin
  - curl -fL -o bin/grabpl https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v3.0.20/grabpl
  - chmod +x bin/grabpl
  image: byrnedo/alpine-curl:0.1.8
  name: grabpl
- commands:
  - . ~/.init-nvm.sh
  - yarn install --frozen-lockfile --no-progress
  depends_on:
  - grabpl
  environment:
    PUPPETEER_CACHE_DIR: /drone/src/cache
  image: grafana/grafana-plugin-ci:1.9.0
  name: yarn-install
- commands:
  - . ~/.init-nvm.sh
  - yarn build
  depends_on:
  - yarn-install
  image: grafana/grafana-plugin-ci:1.9.0
  name: yarn-build
- commands:
  - dockerize -wait http://grafana:3000 -timeout 120s
  image: jwilder/dockerize:0.6.1
  name: wait-for-grafana
- commands:
  - yarn test-ci
  depends_on:
  - wait-for-grafana
  - yarn-build
  environment:
    CI: "true"
    PUPPETEER_CACHE_DIR: /drone/src/cache
  image: us-docker.pkg.dev/grafanalabs-dev/grafana-ci/docker-puppeteer:2.0.0
  name: yarn-test
- commands:
  - . ~/.init-nvm.sh
  - echo "Starting veracode scan..."
  - '# Increase heap size or the scanner will die.'
  - export _JAVA_OPTIONS=-Xmx4g
  - mkdir -p ci/jobs/security_scan
  - curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --skip-compile --quick
    --allow-dirty
  depends_on:
  - yarn-build
  environment:
    SRCCLR_API_TOKEN:
      from_secret: srcclr_api_token
  failure: ignore
  image: grafana/grafana-plugin-ci:1.9.0
  name: security-scan
- commands:
  - . ~/.init-nvm.sh
  - ./scripts/package_target.sh linux-x64-glibc
  - bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc
  - ./scripts/archive_target.sh linux-x64-glibc
  depends_on:
  - yarn-test
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-linux-x64-glibc
- commands:
  - . ~/.init-nvm.sh
  - ./scripts/package_target.sh darwin-x64-unknown
  - bin/grabpl build-plugin-manifest ./dist/plugin-darwin-x64-unknown
  - ./scripts/archive_target.sh darwin-x64-unknown
  depends_on:
  - yarn-test
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-darwin-x64-unknown
- commands:
  - . ~/.init-nvm.sh
  - ./scripts/package_target.sh win32-x64-unknown
  - bin/grabpl build-plugin-manifest ./dist/plugin-win32-x64-unknown
  - ./scripts/archive_target.sh win32-x64-unknown
  depends_on:
  - yarn-test
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-win32-x64-unknown
- commands:
  - . ~/.init-nvm.sh
  - ./scripts/package_target.sh linux-x64-glibc true plugin-linux-x64-glibc-no-chromium
  - bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc-no-chromium
  - ./scripts/archive_target.sh linux-x64-glibc plugin-linux-x64-glibc-no-chromium
  depends_on:
  - yarn-test
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-linux-x64-glibc-no-chromium
- commands:
  - . ~/.init-nvm.sh
  - ./scripts/package_target.sh alpine-x64-unknown true plugin-alpine-x64-no-chromium
  - bin/grabpl build-plugin-manifest ./dist/plugin-alpine-x64-no-chromium
  - ./scripts/archive_target.sh alpine-x64-unknown plugin-alpine-x64-no-chromium
  depends_on:
  - yarn-test
  environment:
    GRAFANA_API_KEY:
      from_secret: grafana_api_key
  image: grafana/grafana-plugin-ci:1.9.0
  name: package-alpine-x64-no-chromium
- commands:
  - ./scripts/generate_md5sum.sh
  - . ./scripts/get_gh_token.sh
  - ./scripts/publish_github_release.sh
  depends_on:
  - package-linux-x64-glibc
  - package-darwin-x64-unknown
  - package-win32-x64-unknown
  - package-linux-x64-glibc-no-chromium
  - package-alpine-x64-no-chromium
  environment:
    GITHUB_APP_ID:
      from_secret: github_app_id
    GITHUB_APP_PRIVATE_KEY:
      from_secret: github_app_private_key
    GITHUB_INSTALLATION_ID:
      from_secret: github_app_installation_id
  image: cibuilds/github:0.13.0
  name: publish_to_github
- commands:
  - ./scripts/build_push_docker.sh
  depends_on:
  - publish_to_github
  environment:
    DOCKER_PASS:
      from_secret: docker_pass
    DOCKER_USER:
      from_secret: docker_user
    IMAGE_NAME: grafana/grafana-image-renderer
  image: google/cloud-sdk:449.0.0
  name: publish_to_docker
  volumes:
  - name: docker
    path: /var/run/docker.sock
- commands:
  - . ~/.init-nvm.sh
  - yarn run create-gcom-plugin-json ${DRONE_COMMIT}
  - yarn run push-to-gcom
  depends_on:
  - publish_to_github
  environment:
    GCOM_PUBLISH_TOKEN:
      from_secret: gcom_publish_token
    GCOM_UAGENT:
      from_secret: gcom_uagent
    GCOM_URL:
      from_secret: gcom_url
  image: grafana/grafana-plugin-ci:1.9.0
  name: publish_to_gcom
trigger:
  branch:
  - master
  event:
  - promote
  target:
  - release
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
get:
  name: .dockerconfigjson
  path: secret/data/common/gcr
kind: secret
name: gcr
---
get:
  name: app-id
  path: ci/data/repo/grafana/grafana-image-renderer/github-app
kind: secret
name: github_app_id
---
get:
  name: private-key
  path: ci/data/repo/grafana/grafana-image-renderer/github-app
kind: secret
name: github_app_private_key
---
get:
  name: app-installation-id
  path: ci/data/repo/grafana/grafana-image-renderer/github-app
kind: secret
name: github_app_installation_id
---
get:
  name: gcom_publish_token
  path: infra/data/ci/drone-plugins
kind: secret
name: gcom_publish_token
---
get:
  name: grafana_api_key
  path: infra/data/ci/drone-plugins
kind: secret
name: grafana_api_key
---
get:
  name: srcclr_api_token
  path: infra/data/ci/drone-plugins
kind: secret
name: srcclr_api_token
---
get:
  name: .dockerconfigjson
  path: secret/data/common/gar
kind: secret
name: gar
---
kind: signature
hmac: 5e72ddb2d00dec40054f0640eb9048e0375790ce7300d0863138e5f98cfb7a0c

...
