---
kind: pipeline
type: docker
name: test-pr

platform:
  os: linux
  arch: amd64

steps:
- name: grabpl
  image: byrnedo/alpine-curl:0.1.8
  commands:
  - mkdir -p bin
  - curl -fL -o bin/grabpl https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v3.0.20/grabpl
  - chmod +x bin/grabpl

- name: yarn-install
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - yarn install --frozen-lockfile --no-progress
  depends_on:
  - grabpl

- name: yarn-build
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - yarn build
  depends_on:
  - yarn-install

- name: package-linux-x64-glibc
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - ../package_target.sh linux-x64-glibc
  - /bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc || true
  - ../archive_target.sh linux-x64-glibc
  depends_on:
  - yarn-build

- name: package-darwin-x64-unknown
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - ../package_target.sh darwin-x64-unknown
  - /bin/grabpl build-plugin-manifest ./dist/plugin-darwin-x64-unknown || true
  - ../archive_target.sh darwin-x64-unknown
  depends_on:
  - yarn-build

- name: package-win32-x64-unknown
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - ../package_target.sh win32-x64-unknown
  - /bin/grabpl build-plugin-manifest ./dist/plugin-win32-x64-unknown || true
  - ../archive_target.sh win32-x64-unknown
  depends_on:
  - yarn-build

- name: package-linux-x64-glibc-no-chromium
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - ../package_target.sh linux-x64-glibc true plugin-linux-x64-glibc-no-chromium
  - /bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc-no-chromium || true
  - ../archive_target.sh linux-x64-glibc plugin-linux-x64-glibc-no-chromium
  depends_on:
  - yarn-build

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

image_pull_secrets:
- dockerconfigjson

node:
  type: no-parallel

trigger:
  event:
  - pull_request

---
kind: pipeline
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: grabpl
  image: byrnedo/alpine-curl:0.1.8
  commands:
  - mkdir -p bin
  - curl -fL -o bin/grabpl https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v3.0.20/grabpl
  - chmod +x bin/grabpl

- name: yarn-install
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - yarn install --frozen-lockfile --no-progress
  depends_on:
  - grabpl

- name: yarn-build
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - yarn build
  depends_on:
  - yarn-install

- name: package-linux-x64-glibc
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - ../package_target.sh linux-x64-glibc
  - /bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc
  - ../archive_target.sh linux-x64-glibc
  depends_on:
  - yarn-build

- name: package-darwin-x64-unknown
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - ../package_target.sh darwin-x64-unknown
  - /bin/grabpl build-plugin-manifest ./dist/plugin-darwin-x64-unknown
  - ../archive_target.sh darwin-x64-unknown
  depends_on:
  - yarn-build

- name: package-win32-x64-unknown
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - ../package_target.sh win32-x64-unknown
  - /bin/grabpl build-plugin-manifest ./dist/plugin-win32-x64-unknown
  - ../archive_target.sh win32-x64-unknown
  depends_on:
  - yarn-build

- name: package-linux-x64-glibc-no-chromium
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - ../package_target.sh linux-x64-glibc true plugin-linux-x64-glibc-no-chromium
  - /bin/grabpl build-plugin-manifest ./dist/plugin-linux-x64-glibc-no-chromium
  - ../archive_target.sh linux-x64-glibc plugin-linux-x64-glibc-no-chromium
  depends_on:
  - yarn-build

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

image_pull_secrets:
- dockerconfigjson

node:
  type: no-parallel

trigger:
  branch:
  - master

---
kind: pipeline
type: docker
name: perform-srcclr-scan

platform:
  os: linux
  arch: amd64

steps:
- name: security-scan
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - echo "Starting veracode scan..."
  - apk add curl
  - "# Increase heap size or the scanner will die."
  - export _JAVA_OPTIONS=-Xmx4g
  - mkdir -p ci/jobs/security_scan
  - curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --skip-compile --quick --allow-dirty
  failure: ignore

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

image_pull_secrets:
- dockerconfigjson

node:
  type: no-parallel

trigger:
  branch:
  - master
  event:
  - push

---
kind: secret
name: github_token

get:
  path: infra/data/ci/drone-plugins
  name: github_token

---
kind: secret
name: srcclr_api_token

get:
  path: infra/data/ci/drone-plugins
  name: srcclr_api_token

---
kind: secret
name: dockerconfigjson

get:
  path: secret/data/common/gcr
  name: .dockerconfigjson

---
kind: signature
hmac: 95818b246d4aeea7bf1a2b9132bf445927f712bef20d9e6fd63f0f292029beff

...
