version: '2'

services:
  docker-puppeteer:
    image: grafana/docker-puppeteer:pre-node-20@sha256:77451c4522c5a7bb00aad3fe9fa61eceef208306a9146caee7b6dc4a20cf261c
    volumes:
      - "../../..:/drone/src"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    entrypoint: bash
  grafana:
    image: grafana/grafana-enterprise:latest@sha256:1645b1867318ef7697c86c1f5e43a3c6c410124307486c1d6e8b77ea7ee9e563
    ports:
      - 3000:3000
    environment:
      GF_FEATURE_TOGGLES_ENABLE: renderAuthJWT
    volumes:
      - ../test/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ../../../scripts/drone/provisioning/dashboards:/usr/share/grafana/dashboards
      - ../../../scripts/drone/provisioning/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
