{
 "title": "Image Render Service",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(grafana_image_renderer_browser_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\", pod=~\"^grafana-render-service-.*\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"^grafana-render-service-.*\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(grafana_image_renderer_browser_info{cluster=\"$cluster\",namespace=\"$namespace\"} > 0)"
    }
   ]
  },
  {
   "title": "Browser version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1, grafana_image_renderer_browser_info{cluster=\"$cluster\",namespace=\"$namespace\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Requests per second (by status)",
   "type": "graph",
   "description": "Average requests per second during past interval grouped by status codes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (label_replace(label_replace(rate(grafana_image_renderer_service_http_request_duration_seconds_count{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]), \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"), \"status\", \"${1}\",   \"status_code\", \"([a-z]+)\"))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum without(instance,status_code, pod)(\n    rate(grafana_image_renderer_service_http_request_duration_seconds_bucket{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, \n  sum without(instance,status_code, pod)(\n    rate(grafana_image_renderer_service_http_request_duration_seconds_bucket{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "sum without(instance,status_code, pod) (rate(grafana_image_renderer_service_http_request_duration_seconds_sum{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) \n/ \nsum without(instance,status_code, pod) (rate(grafana_image_renderer_service_http_request_duration_seconds_count{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Requests per second (by instance)",
   "type": "graph",
   "description": "Average requests per second during past interval grouped by status codes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (irate(grafana_image_renderer_service_http_request_duration_seconds_count{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request latency distribution",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(grafana_image_renderer_service_http_request_duration_seconds_bucket{cluster=\"$cluster\",namespace=\"$namespace\"}[$__interval]) * $__interval_ms / 1000) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\", container=\"grafana-render-service\", pod=~\"^$pod.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container_name=\"grafana-render-service\", pod=~\"^$pod.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Errors per second (all clusters)",
   "type": "graph",
   "description": "Average requests per second during past interval grouped by status codes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) (label_replace(label_replace(rate(grafana_image_renderer_service_http_request_duration_seconds_count{status_code!=\"200\"}[$__interval]), \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"), \"status\", \"${1}\",   \"status_code\", \"([a-z]+)\"))",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}