# https://github.com/grafana/tempo/blob/main/example/docker-compose/shared/prometheus.yaml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]
  - job_name: "image-renderer"
    static_configs:
      - targets: ["renderer:8081"]
