services:
  grafana:
    image: grafana/grafana-enterprise:latest@sha256:02b49ed5d9210bdd1a70600f2c906e74e8df2846b18ac58997ca724dfe2db593
    ports:
      - 3000:3000
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug

  renderer:
    build:
      context: ../../../
      dockerfile: Dockerfile
    ports:
      - 8081
    environment:
      ENABLE_METRICS: 'true'
