services:
  grafana:
    image: grafana/grafana-enterprise:latest@sha256:1d6b24fd4121d97bde0dea8aa19a357306a48dbfb7f61303649c4b6db5d327b7
    ports:
      - 3000:3000
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug

  renderer:
    build:
      context: ../../../
      dockerfile: Dockerfile
    ports:
      - 8081
    environment:
      ENABLE_METRICS: 'true'
