services:
  grafana:
    image: grafana/grafana-enterprise:latest@sha256:6f9edf04510e8d219131ee6da55af53ea13e53699d784470ac41e2f1e7733dc8
    ports:
      - 3000:3000
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug

  renderer:
    build:
      context: ../../../
      dockerfile: Dockerfile
    ports:
      - 8081
    environment:
      ENABLE_METRICS: 'true'
