name: Snyk Monitor Scanning

on:
  release:
    types: [published] 
  push:
    branches:
      - 'master'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  snyk-scan-ci:
    uses: 'grafana/security-github-actions/.github/workflows/snyk_monitor.yml@main'
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
